const resList = [
    {
        id: 101,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/sv4zxb9jn3p8ocrltj3i",
        Name: "Dominos",
        rating: 4.8,
        time: 28,
        dishName: "Pepperoni Pizza",
        place: "Downtown Square",
    },
    {
        id: 102,
        img: "https://apicms.thestar.com.my/uploads/images/2023/02/25/1956254.jpg",
        Name: "KFC",
        rating: 3.5,
        time: 38,
        dishName: "Chicken Wings",
        place: "City Center",
    },
    {
        id: 103,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/wsp5vreexpl64nq41m1h",
        Name: "Red Bucket",
        rating: 4.2,
        time: 40,
        dishName: "Lasagna",
        place: "Riverside Plaza",
    },
    {
        id: 104,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/2b8b717cfc1d7aac9c1c9d16594735f8",
        Name: "Burger King",
        rating: 4.1,
        time: 25,
        dishName: "Big King",
        place: "Mall Food Court",
    },
    {
        id: 105,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/wsp5vreexpl64nq41m1h",
        Name: "Red Bucket",
        rating: 4.5,
        time: 40,
        dishName: "Penne Alfredo",
        place: "Riverside Plaza",
    },
    {
        id: 106,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/2b8b717cfc1d7aac9c1c9d16594735f8",
        Name: "Burger King",
        rating: 3.9,
        time: 25,
        dishName: "Chicken Royale",
        place: "Mall Food Court",
    },
    {
        id: 107,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/sv4zxb9jn3p8ocrltj3i",
        Name: "Pizza",
        rating: 4.6,
        time: 40,
        dishName: "Spicy Bolognese",
        place: "Riverside Plaza",
    },
    {
        id: 108,
        img: "https://apicms.thestar.com.my/uploads/images/2023/02/25/1956254.jpg",
        Name: "KFC",
        rating: 3.7,
        time: 25,
        dishName: "Veggie Whopper",
        place: "Mall Food Court",
    },
];

export default resList;
